### ISSUE TITLE
Se-dark AU theme

### ISSUE THREAD

**Issue by ghost** [zacharee/se-dark#3]
It seems to have little gray dots on it for me. Are those removable?

**Comment by zacharee** [comment]
Gray dots where?

**Comment by zacharee** [comment]
Are they where the site background is? The CSS is meant to remove the image that places those in. What browser is this?

**Comment by KazWolfe** [comment]
Without any sort of indication as to what these grey dots are, or where they exist, or anything else, I'm electing to close this ticket as invalid. If feedback is provided to actually explain what and where this problem is happening, submit a new comment to this issue, and I will re-open accordingly.
